# Generated by Django 5.0.6 on 2024-05-21 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='speakers/'),
            preserve_default=False,
        ),
    ]
