# Generated by Django 5.0.6 on 2024-05-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_speaker_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='speakername',
            new_name='eventname',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_photo',
        ),
    ]
